sudo: required
services:
    - docker
    
before_install:
    - docker build -t thomasknott/docker-react -f Dockerfile.dev .
    
script:
    - docker run thomasknott/docker-react npm run test -- --coverage
    